add fetch query ✔
reactplay/backend-api pull request #2
Opened 2022-06-08 13:08 UTC by murtuzaalisurti

2022-06-08 13:42 UTC, atapas requested changes

2022-06-08 13:42 UTC, atapas commented on queries/fetch-plays.gql
> +  plays {
@murtuzaalisurti made some modifications to the query..

```gql
query Fetch_Plays {
  plays {
    blog
    component
    cover
    created_at
    description
    featured
    github
    id
    language
    level {
      id
      name
    }
    name
    path
    play_tags {
      tag {
        id
        name
      }
    }
    updated_at
    user {
      id
      displayName
      avatarUrl
      userProviders {
        accessToken
      }
    }
    video
  }
}
```

Kindly test it.

Also make sure the response data value is correct. else when we integrate it will show wrong data in the UI

2022-06-08 14:32 UTC, murtuzaalisurti commented on queries/fetch-plays.gql
> +  plays {
LGTM

2022-06-09 02:28 UTC, atapas approved these changes

2022-06-09 02:28 UTC, merged